//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOK()
        {
            this.ORDERS = new HashSet<ORDERS>();
        }
    
        public decimal BOOKID { get; set; }
        public string TITLE { get; set; }
        public decimal AUTHORID { get; set; }
        public decimal PUBLISHERID { get; set; }
        public decimal GENREID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> RATING { get; set; }
        public Nullable<decimal> PRICE { get; set; }
    
        public virtual AUTHOR AUTHOR { get; set; }
        public virtual GENRE GENRE { get; set; }
        public virtual PUBLISHER PUBLISHER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS> ORDERS { get; set; }
    }
}
